Prop explanation
rdawg-pidinst/schema pull request #64
Opened 2022-02-11 17:33 UTC by RKrahl

- Add an explanation that there is no generally applicable list of Instrument types for all scientific domains, but it is recommended to use the one(s) relevant to the domain if they exist.
- Move the remarks for `ownerIdentifierType`, `manufacturerIdentifierType`, `modelIdentifierType`, and `instrumentTypeIdentifierType` recommending to use the PID types defined in the controlled list of values for `relatedIdentifierType` if applicable, from Table 2 to the text.

Close #62.

2022-02-11 17:51 UTC, markusstocker commented on doc/schema.tex
> +instrument types for some scientific domains.  So if the instrument is
No "So", start with "If the instrument"

2022-02-11 17:53 UTC, markusstocker requested changes
One minor comment, Lou may have further language suggestions. Overall it looks good to me.

2022-02-11 17:58 UTC, RKrahl commented on doc/schema.tex
> +instrument types for some scientific domains.  So if the instrument is
Done.

2022-02-14 09:27 UTC, RKrahl commented
As suggested by Jens Klump, I added a sentence that future versions of the schema may change free text properties to use controlled vocabularies.

2022-02-18 15:03 UTC, merged